INSERT INTO services (name, duration, price, tenant_id, created_at, updated_at) VALUES
('Men''s Haircut', 30, 25.00, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Beard Trim', 20, 15.00, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hair + Beard Combo', 45, 35.00, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Kids Haircut', 25, 20.00, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hair Styling', 40, 30.00, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Shave', 30, 25.00, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hair Coloring', 90, 70.00, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Facial', 45, 40.00, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
